version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: 192.168.99.100:5000/friendlyhello:latest
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
      - "80:80"
    networks:
      - webnet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      # use socket on host instead of containers own
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
      # run only on manager node on swarm
        constraints: [node.role == manager]
    networks:
      - webnet
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      # must persist on host instead of container, or else data will be wiped
      # when container dies.
      - "/home/docker/data:/data"
    deploy:
      placement:
        # must run on manager which also makes it persist on same host!
        constraints: [node.role == manager]
    command: redis-server --appendonly yes
    networks:
      - webnet
networks:
  webnet:
